name: 'AutoReview by OpenAI'
description: 'This action is an action that uses OpenAI to perform an auto-review.'
inputs:
  api-key:
    description: >
      OpenAI の API キーを指定します。
    required: true
  base-sha:
    description: >
      ベースとなるコミットの SHA を指定します。
    required: true
    default: ${{ github.event.pull_request.base.sha }}
outputs:
  review:
    description: >
      オートレビューの結果を出力します。
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: "box"
  color: "orange"
