name: 'AutoReview by OpenAI'
description: 'This action is an action that uses OpenAI to perform an auto-review.'
inputs:
  openai-api-key:
    description: >
      OpenAI の API キーを指定します。
    required: true
  base-sha:
    description: >
      ベースとなるコミットの SHA を指定します。
    required: true
    default: ${{ github.event.pull_request.base.sha }}
  github-token:
    description: >
      GitHub のトークンを指定します。
    required: true
    default: ${{ github.token }}
  pull-request-url:
    description: >
      プルリクエストの URL を指定します。
    required: true
    default: ${{ github.event.pull_request.html_url }}
  target:
    description: >
      レビュー対象のファイルを指定します。
    required: true
outputs:
  review:
    description: >
      オートレビューの結果を出力します。
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: "box"
  color: "orange"
